services:
  print_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: print_server
    ports:
      - "80:80"
    privileged: true
    devices:
      - /dev/bus/usb/004/007:/dev/usb/001  # USB Printer
    volumes:
      - /sys/class/pwm/pwmchip0/pwm1/:/sys/class/pwm/pwmchip0/pwm1
    restart: always
