services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: print_server
    ports:
      - "80:80"
    privileged: true
    devices:
      - /dev/bus/usb:/dev/usb  # USB Printer
    # volumes:
      # - /sys/class/pwm/pwmchip0/pwm1/:/sys/class/pwm/pwmchip0/pwm1
    restart: always
