services:
  fastapi:
    container_name: print_server
    build: .
    env_file: web/.env
    environment:
      - BACKEND=${BACKEND}
      - PRINTER=${PRINTER}
      - MEDIA=${MEDIA}
      - FONT=${FONT}
      - VENDOR_ID=${VENDOR_ID}
      - PRODUCT_ID=${PRODUCT_ID}
      - MOTOR_INITIAL=${MOTOR_INITIAL}
      - MOTOR_FINAL=${MOTOR_FINAL}
    ports:
      - "80:80"
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb  # USB Printer
    volumes:
      - /sys/class/pwm:/sys/class/pwm
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 10s
